// Generated by gencpp from file race_2019/pid_param.msg
// DO NOT EDIT!


#ifndef RACE_2019_MESSAGE_PID_PARAM_H
#define RACE_2019_MESSAGE_PID_PARAM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace race_2019
{
template <class ContainerAllocator>
struct pid_param_
{
  typedef pid_param_<ContainerAllocator> Type;

  pid_param_()
    : kp(0.0)
    , ki(0.0)
    , kd(0.0)
    , servo_offset(0.0)
    , alpha(0.0)
    , beta(0.0)
    , velocity(0.0)
    , lb(0.0)  {
    }
  pid_param_(const ContainerAllocator& _alloc)
    : kp(0.0)
    , ki(0.0)
    , kd(0.0)
    , servo_offset(0.0)
    , alpha(0.0)
    , beta(0.0)
    , velocity(0.0)
    , lb(0.0)  {
  (void)_alloc;
    }



   typedef float _kp_type;
  _kp_type kp;

   typedef float _ki_type;
  _ki_type ki;

   typedef float _kd_type;
  _kd_type kd;

   typedef float _servo_offset_type;
  _servo_offset_type servo_offset;

   typedef float _alpha_type;
  _alpha_type alpha;

   typedef float _beta_type;
  _beta_type beta;

   typedef float _velocity_type;
  _velocity_type velocity;

   typedef float _lb_type;
  _lb_type lb;




  typedef boost::shared_ptr< ::race_2019::pid_param_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::race_2019::pid_param_<ContainerAllocator> const> ConstPtr;

}; // struct pid_param_

typedef ::race_2019::pid_param_<std::allocator<void> > pid_param;

typedef boost::shared_ptr< ::race_2019::pid_param > pid_paramPtr;
typedef boost::shared_ptr< ::race_2019::pid_param const> pid_paramConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::race_2019::pid_param_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::race_2019::pid_param_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace race_2019

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'race_2019': ['/home/ubuntu/catkin_ws/src/catkin_src_packages/race_2019/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::race_2019::pid_param_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::race_2019::pid_param_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::race_2019::pid_param_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::race_2019::pid_param_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::race_2019::pid_param_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::race_2019::pid_param_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::race_2019::pid_param_<ContainerAllocator> >
{
  static const char* value()
  {
    return "92724b2750bafc1f0a00e32e7efe65aa";
  }

  static const char* value(const ::race_2019::pid_param_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x92724b2750bafc1fULL;
  static const uint64_t static_value2 = 0x0a00e32e7efe65aaULL;
};

template<class ContainerAllocator>
struct DataType< ::race_2019::pid_param_<ContainerAllocator> >
{
  static const char* value()
  {
    return "race_2019/pid_param";
  }

  static const char* value(const ::race_2019::pid_param_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::race_2019::pid_param_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 kp\n\
float32 ki\n\
float32 kd\n\
float32 servo_offset\n\
float32 alpha\n\
float32 beta\n\
float32 velocity\n\
float32 lb\n\
\n\
";
  }

  static const char* value(const ::race_2019::pid_param_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::race_2019::pid_param_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.kp);
      stream.next(m.ki);
      stream.next(m.kd);
      stream.next(m.servo_offset);
      stream.next(m.alpha);
      stream.next(m.beta);
      stream.next(m.velocity);
      stream.next(m.lb);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pid_param_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::race_2019::pid_param_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::race_2019::pid_param_<ContainerAllocator>& v)
  {
    s << indent << "kp: ";
    Printer<float>::stream(s, indent + "  ", v.kp);
    s << indent << "ki: ";
    Printer<float>::stream(s, indent + "  ", v.ki);
    s << indent << "kd: ";
    Printer<float>::stream(s, indent + "  ", v.kd);
    s << indent << "servo_offset: ";
    Printer<float>::stream(s, indent + "  ", v.servo_offset);
    s << indent << "alpha: ";
    Printer<float>::stream(s, indent + "  ", v.alpha);
    s << indent << "beta: ";
    Printer<float>::stream(s, indent + "  ", v.beta);
    s << indent << "velocity: ";
    Printer<float>::stream(s, indent + "  ", v.velocity);
    s << indent << "lb: ";
    Printer<float>::stream(s, indent + "  ", v.lb);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RACE_2019_MESSAGE_PID_PARAM_H
