// Generated by gencpp from file race_2019/pid_input.msg
// DO NOT EDIT!


#ifndef RACE_2019_MESSAGE_PID_INPUT_H
#define RACE_2019_MESSAGE_PID_INPUT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace race_2019
{
template <class ContainerAllocator>
struct pid_input_
{
  typedef pid_input_<ContainerAllocator> Type;

  pid_input_()
    : wdr(0.0)
    , wdl(0.0)
    , dl(0.0)
    , dfl(0.0)
    , dfr(0.0)
    , dr(0.0)  {
    }
  pid_input_(const ContainerAllocator& _alloc)
    : wdr(0.0)
    , wdl(0.0)
    , dl(0.0)
    , dfl(0.0)
    , dfr(0.0)
    , dr(0.0)  {
  (void)_alloc;
    }



   typedef float _wdr_type;
  _wdr_type wdr;

   typedef float _wdl_type;
  _wdl_type wdl;

   typedef float _dl_type;
  _dl_type dl;

   typedef float _dfl_type;
  _dfl_type dfl;

   typedef float _dfr_type;
  _dfr_type dfr;

   typedef float _dr_type;
  _dr_type dr;




  typedef boost::shared_ptr< ::race_2019::pid_input_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::race_2019::pid_input_<ContainerAllocator> const> ConstPtr;

}; // struct pid_input_

typedef ::race_2019::pid_input_<std::allocator<void> > pid_input;

typedef boost::shared_ptr< ::race_2019::pid_input > pid_inputPtr;
typedef boost::shared_ptr< ::race_2019::pid_input const> pid_inputConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::race_2019::pid_input_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::race_2019::pid_input_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace race_2019

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'race_2019': ['/home/ubuntu/catkin_ws/src/catkin_src_packages/race_2019/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::race_2019::pid_input_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::race_2019::pid_input_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::race_2019::pid_input_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::race_2019::pid_input_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::race_2019::pid_input_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::race_2019::pid_input_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::race_2019::pid_input_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bbb538dc9d9e4255bee8560be6747083";
  }

  static const char* value(const ::race_2019::pid_input_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbbb538dc9d9e4255ULL;
  static const uint64_t static_value2 = 0xbee8560be6747083ULL;
};

template<class ContainerAllocator>
struct DataType< ::race_2019::pid_input_<ContainerAllocator> >
{
  static const char* value()
  {
    return "race_2019/pid_input";
  }

  static const char* value(const ::race_2019::pid_input_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::race_2019::pid_input_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
float32 wdr\n\
float32 wdl\n\
float32 dl\n\
float32 dfl\n\
float32 dfr\n\
float32 dr\n\
";
  }

  static const char* value(const ::race_2019::pid_input_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::race_2019::pid_input_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.wdr);
      stream.next(m.wdl);
      stream.next(m.dl);
      stream.next(m.dfl);
      stream.next(m.dfr);
      stream.next(m.dr);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pid_input_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::race_2019::pid_input_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::race_2019::pid_input_<ContainerAllocator>& v)
  {
    s << indent << "wdr: ";
    Printer<float>::stream(s, indent + "  ", v.wdr);
    s << indent << "wdl: ";
    Printer<float>::stream(s, indent + "  ", v.wdl);
    s << indent << "dl: ";
    Printer<float>::stream(s, indent + "  ", v.dl);
    s << indent << "dfl: ";
    Printer<float>::stream(s, indent + "  ", v.dfl);
    s << indent << "dfr: ";
    Printer<float>::stream(s, indent + "  ", v.dfr);
    s << indent << "dr: ";
    Printer<float>::stream(s, indent + "  ", v.dr);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RACE_2019_MESSAGE_PID_INPUT_H
