# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from race_2019/pid_input.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class pid_input(genpy.Message):
  _md5sum = "bbb538dc9d9e4255bee8560be6747083"
  _type = "race_2019/pid_input"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """
float32 wdr
float32 wdl
float32 dl
float32 dfl
float32 dfr
float32 dr
"""
  __slots__ = ['wdr','wdl','dl','dfl','dfr','dr']
  _slot_types = ['float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       wdr,wdl,dl,dfl,dfr,dr

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(pid_input, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.wdr is None:
        self.wdr = 0.
      if self.wdl is None:
        self.wdl = 0.
      if self.dl is None:
        self.dl = 0.
      if self.dfl is None:
        self.dfl = 0.
      if self.dfr is None:
        self.dfr = 0.
      if self.dr is None:
        self.dr = 0.
    else:
      self.wdr = 0.
      self.wdl = 0.
      self.dl = 0.
      self.dfl = 0.
      self.dfr = 0.
      self.dr = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_6f.pack(_x.wdr, _x.wdl, _x.dl, _x.dfl, _x.dfr, _x.dr))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.wdr, _x.wdl, _x.dl, _x.dfl, _x.dfr, _x.dr,) = _struct_6f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_6f.pack(_x.wdr, _x.wdl, _x.dl, _x.dfl, _x.dfr, _x.dr))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.wdr, _x.wdl, _x.dl, _x.dfl, _x.dfr, _x.dr,) = _struct_6f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_6f = struct.Struct("<6f")
